sudo: required
services:
  - docker

before_install:
  - docker build -t jlangdon90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jlangdon90/react-test npm test -- --coverage

after_success:
  - docker build -t jlangdon90/multi-client ./client
  - docker build -t jlangdon90/multi-nginx ./nginx
  - docker build -t jlangdon90/multi-server ./server
  - docker build -t jlangdon90/multi-worker ./worker
  # log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to Docker hub
  - docker push jlangdon90/multi-client
  - docker push jlangdon90/multi-nginx
  - docker push jlangdon90/multi-server
  - docker push jlangdon90/multi-worker
  
